using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using UnityEngine;

namespace  URS
{
    /// <summary>
    /// A storage class used to gather data about an Addressable build.
    /// </summary>
    [Serializable]
    public class BuildLayout
    {
        /// <summary>
        /// Information about the AssetBundleObject
        /// </summary>
        [Serializable]
        public class AssetBundleObjectInfo
        {
            /// <summary>
            /// The size, in bytes, of the AssetBundleObject
            /// </summary>
            public ulong Size;
        }
        /*
        /// <summary>
        /// Data about the AddressableAssetGroup that gets processed during a build.
        /// </summary>
        [Serializable]
        public class Group
        {
            /// <summary>
            /// The Name of the AdressableAssetGroup
            /// </summary>
            public string Name;
            /// <summary>
            /// The Guid of the AddressableAssetGroup
            /// </summary>
            public string Guid;
            /// <summary>
            /// The packing mode as defined by the BundledAssetGroupSchema on the AddressableAssetGroup
            /// </summary>
            public string PackingMode;

            /// <summary>
            /// A list of the AssetBundles associated with the Group
            /// </summary>
            [SerializeReference]
            public List<Bundle> Bundles = new List<Bundle>();
            /// <summary>
            /// Data about the AddressableAssetGroupSchemas associated with the Group
            /// </summary>
            [SerializeReference]
            public List<SchemaData> Schemas = new List<SchemaData>();
        }

        /// <summary>
        /// Data container for AddressableAssetGroupSchemas
        /// </summary>
        [Serializable]
        public class SchemaData
        {
            /// <summary>
            /// The Guid of the AddressableAssetGroupSchema
            /// </summary>
            public string Guid;
            /// <summary>
            /// The class type of the AddressableAssetGroupSchema
            /// </summary>
            public string Type;

            /// <summary>
            /// These key-value-pairs include data about the AddressableAssetGroupSchema, such as PackingMode and Compression.
            /// </summary>
            [SerializeReference]
            public List<Tuple<string, string>> KvpDetails = new List<Tuple<string, string>>();
        }
        */
        /// <summary>
        /// Data store for AssetBundle information.
        /// </summary>
        [Serializable]
        public class Bundle
        {
            /// <summary>
            /// The name of the AssetBundle
            /// </summary>
           [SerializeField]
            public string Name;
            /// <summary>
            /// The file size of the AssetBundle on disk, in bytes
            /// </summary>
            [SerializeField]
            public ulong FileSize;
            /// <summary>
            /// The Compression method used for the AssetBundle.
            /// </summary>
            [SerializeField]
            public string Compression;

            /// <summary>
            /// A reference to the Group data that this AssetBundle was generated from
            /// </summary>
            //[SerializeReference]
            //public Group Group;

            /// <summary>
            /// List of the Files referenced by the AssetBundle
            /// </summary>
            [SerializeReference]
            [NonSerialized]
            public List<File> Files = new List<File>();

            [SerializeField]
            public string[] files;
            /// <summary>
            /// A list of the direct dependencies of the AssetBundle
            /// </summary>
           // [SerializeReference]
            //public List<Bundle> Dependencies;

            /// <summary>
            /// The full dependency list, flattened into a list
            /// </summary>
            [SerializeReference]
            [NonSerialized]
            public List<Bundle> ExpandedDependencies;


            [SerializeField]
            public string[] expandedDependencies;

            private bool prepared= false;
            public void PrepareSerialize()
            {
                if(prepared) return;
                prepared = true;

                Files.ForEach(f => f.PrepareSerialize());
                ExpandedDependencies.ForEach(f => f.PrepareSerialize());

                files = Files.Select(file => file.Name).ToArray();
                expandedDependencies= ExpandedDependencies.Select(ed => ed.Name).ToArray();
            }
        }

        /// <summary>
        /// Data store for resource files generated by the build pipeline and referenced by a main File
        /// </summary>
        [Serializable]
        public class SubFile
        {
            /// <summary>
            /// The name of the sub-file
            /// </summary>
            public string Name;
            /// <summary>
            /// If the main File is a serialized file, this will be true.
            /// </summary>
            public bool IsSerializedFile;
            /// <summary>
            /// The size of the sub-file, in bytes
            /// </summary>
            public ulong Size;
        }

        /// <summary>
        /// Data store for the main File created for the AssetBundle
        /// </summary>
        [Serializable]
        public class File
        {
            /// <summary>
            /// The name of the File.
            /// </summary>
            [SerializeField]
            public string Name;

            /// <summary>
            /// The AssetBundle data that relates to a built file.
            /// </summary>
            [NonSerialized] 
            [SerializeReference]
            public Bundle Bundle;

            [SerializeField]
            public string BundleName;

            /// <summary>
            /// List of the resource files created by the build pipeline that a File references
            /// </summary>
            [SerializeReference]
            [NonSerialized]
            public List<SubFile> SubFiles = new List<SubFile>();


            [SerializeField]
            public SubFile[] subFiles;
            /// <summary>
            /// A list of the explicit asset defined in the AssetBundle
            /// </summary>
            [SerializeReference]
            [NonSerialized]
            public List<ExplicitAsset> Assets = new List<ExplicitAsset>();

            [SerializeField]
            public string[] assets;

            /// <summary>
            /// A list of implicit assets built into the AssetBundle, typically through references by Assets that are explicitly defined.
            /// </summary>
            [SerializeReference]
            [NonSerialized]
            public List<DataFromOtherAsset> OtherAssets = new List<DataFromOtherAsset>();

            [SerializeField]
            public DataFromOtherAsset[] otherAssets;
            /// <summary>
            /// The final filename of the AssetBundle file
            /// </summary>
            [SerializeField]
            public string WriteResultFilename;
            /// <summary>
            /// Data about the AssetBundleObject
            /// </summary>
            [SerializeField]
            public AssetBundleObjectInfo BundleObjectInfo;
            /// <summary>
            /// The size of the data that needs to be preloaded for this File.
            /// </summary>
            [SerializeField]
            public int PreloadInfoSize;
            /// <summary>
            /// The number of Mono scripts referenced by the File
            /// </summary>
            [SerializeField]
            public int MonoScriptCount;
            /// <summary>
            /// The size of the Mono scripts referenced by the File
            /// </summary>
            [SerializeField]
            public ulong MonoScriptSize;



            private bool prepared = false;
            public void PrepareSerialize()
            {
                if (prepared) return;
                prepared = true;

                if (Bundle != null) 
                {
                    Bundle.PrepareSerialize();
                    BundleName = Bundle.Name;
                }
               

                OtherAssets.ForEach(asset => asset.PrepareSerialize());
                Assets.ForEach((asset) => { asset.PrepareSerialize(); });

               
                otherAssets = OtherAssets.ToArray();
                assets= Assets.Select(ea=>ea.AssetPath).ToArray();
            }
        }

        /// <summary>
        /// Data store for Assets explicitly defined in an AssetBundle
        /// </summary>
        [Serializable]
        public class ExplicitAsset
        {
            /// <summary>
            /// The Asset Guid.
            /// </summary>
            [SerializeField]
            public string Guid;
            /// <summary>
            /// The Asset path on disk
            /// </summary>
            /// 
            [SerializeField]
            public string AssetPath;
            /// <summary>
            /// The Addressable address defined in the Addressable Group window for an Asset.
            /// </summary>
            [SerializeField]
            public string AddressableName;
            /// <summary>
            /// The size of the file on disk.
            /// </summary>
            [SerializeField]
            public ulong SerializedSize;
            /// <summary>
            /// The size of the streamed Asset.
            /// </summary>
            [SerializeField]
            public ulong StreamedSize;
            /// <summary>
            /// The file that the Asset was added to
            /// </summary>
            [SerializeReference]
            [NonSerialized]
            public File File;


            [SerializeField]
            public string file;
            /// <summary>
            /// List of data from other Assets referenced by an Asset in the File
            /// </summary>
            [SerializeReference]
            [NonSerialized]
            public List<DataFromOtherAsset> InternalReferencedOtherAssets = new List<DataFromOtherAsset>();

            [SerializeField]
            public DataFromOtherAsset[] internalReferencedOtherAssets;

            /// <summary>
            /// List of explicit Assets in the File
            /// </summary>
            [SerializeReference]
            [NonSerialized]
            public List<ExplicitAsset> InternalReferencedExplicitAssets = new List<ExplicitAsset>();

            [SerializeField]
            public string[] internalReferencedExplicitAssets;
            /// <summary>
            /// List of Assets referenced by the File, but not included in the File.
            /// </summary>
            [SerializeReference]
            [NonSerialized]
            public List<ExplicitAsset> ExternallyReferencedAssets = new List<ExplicitAsset>();


            [SerializeField]
            public string[] externallyReferencedAssets;

            private bool prepared = false;
            public void PrepareSerialize()
            {
                if (prepared) { return; }
                prepared = true;

                if (File != null) 
                {
                    File.PrepareSerialize();
                    file = File.Name;
                }
                
                InternalReferencedOtherAssets.ForEach((roa)=>roa.PrepareSerialize());
                internalReferencedOtherAssets= InternalReferencedOtherAssets.ToArray();

                InternalReferencedExplicitAssets.ForEach((roa) => roa.PrepareSerialize());
                internalReferencedExplicitAssets = InternalReferencedExplicitAssets.Select(ea=>ea.AssetPath).ToArray();


                ExternallyReferencedAssets.ForEach((roa) => roa.PrepareSerialize());
                externallyReferencedAssets = ExternallyReferencedAssets.Select(ea => ea.AssetPath).ToArray();
            }
        }

        /// <summary>
        /// Data store for implicit Asset references
        /// </summary>
        [Serializable]
        public class DataFromOtherAsset
        {
            /// <summary>
            /// The Guid of the Asset
            /// </summary>
            [SerializeField]
            public string AssetGuid;
            /// <summary>
            /// The Asset path on disk
            /// </summary
            [SerializeField]
            public string AssetPath;

            /// <summary>
            /// A list of Assets that reference this data
            /// </summary>
            [SerializeReference]
            [NonSerialized]
            public List<ExplicitAsset> ReferencingAssets = new List<ExplicitAsset>();

            [SerializeField]
            public string[] referencingAssets;
            /// <summary>
            /// The number of Objects in the data
            /// </summary>
            [SerializeField]
            public int ObjectCount;
            /// <summary>
            /// The size of the data on disk
            /// </summary>
            [SerializeField]
            public ulong SerializedSize;
            /// <summary>
            /// The size of the streamed data
            /// </summary>
            [SerializeField]
            public ulong StreamedSize;

            private bool prepared = false;
            public void PrepareSerialize()
            {
                if (prepared) return;
                prepared = true;

                ReferencingAssets.ForEach((ea)=>ea.PrepareSerialize());
                var list = ReferencingAssets.Select(ea=>ea.AssetPath);
                referencingAssets= list.ToArray();
            }
        }

        /// <summary>
        /// The Addressable Groups that reference this data
        /// </summary>
       // [SerializeReference]
        //public List<Group> Groups = new List<Group>();

        /// <summary>
        /// List of AssetBundles this data was built into
        /// </summary>
        //[SerializeReference]
       // public List<Bundle> BuiltInBundles = new List<Bundle>();
    }

    /// <summary>
    /// Utility used to quickly reference data built with the build pipeline
    /// </summary>
    /// 
    [Serializable]
    public class LayoutLookupTables
    {
        /// <summary>
        /// The AssetBundle name to the Bundle data map.
        /// </summary>
        [NonSerialized]
        public Dictionary<string, BuildLayout.Bundle> Bundles = new Dictionary<string, BuildLayout.Bundle>();
        /// <summary>
        /// File name to File data map.
        /// </summary>
        [NonSerialized]
        public Dictionary<string, BuildLayout.File> Files = new Dictionary<string, BuildLayout.File>();
        /// <summary>
        /// Guid to ExplicitAsset data map.
        /// </summary>
        /// 
        [NonSerialized]
        public Dictionary<string, BuildLayout.ExplicitAsset> GuidToExplicitAsset = new Dictionary<string, BuildLayout.ExplicitAsset>();
        /// <summary>
        /// Group name to Group data map.
        /// </summary>
       // public Dictionary<string, BuildLayout.Group> GroupLookup = new Dictionary<string, BuildLayout.Group>();
       
        [SerializeField]
        public BuildLayout.Bundle[] bundles;

        [SerializeField]
        public BuildLayout.File[] files;

        [SerializeField]
        public BuildLayout.ExplicitAsset[] explicitAssets;

        public void PrepareSerialize() 
        {
            var bundleList = Bundles.Values.ToList();
            bundleList.ForEach(bundle => { bundle.PrepareSerialize(); });
            bundles = bundleList.ToArray();

            var fileList = Files.Values.ToList();
            fileList.ForEach(file => { file.PrepareSerialize(); });
            files = fileList.ToArray();

            var guidToExplicit = GuidToExplicitAsset.Values.ToList();
            guidToExplicit.ForEach(ea => { ea.PrepareSerialize(); });
            explicitAssets = guidToExplicit.ToArray();
        }

    }
    /// <summary>
    /// Helper methods for gathering data about a build layout.
    /// </summary>
    public class BuildLayoutHelpers
    {
        /// <summary>
        /// Gather a list of Explicit Assets defined in a BuildLayout
        /// </summary>
        /// <param name="layout">The BuildLayout generated during a build</param>
        /// <returns>A list of ExplicitAsset data.</returns>
        public static IEnumerable<BuildLayout.ExplicitAsset> EnumerateAssets(LayoutLookupTables layout)
        {
            return EnumerateBundles(layout).SelectMany(b => b.Files).SelectMany(f => f.Assets);
        }

        /// <summary>
        /// Gather a list of Explicit Assets defined in a Bundle
        /// </summary>
        /// <param name="bundle">The Bundle data generated during a build</param>
        /// <returns>A list of ExplicitAssets defined in the Bundle</returns>
        public static IEnumerable<BuildLayout.ExplicitAsset> EnumerateAssets(BuildLayout.Bundle bundle)
        {
            return bundle.Files.SelectMany(f => f.Assets);
        }

        /// <summary>
        /// Gather a list of Bundle data defined in a BuildLayout
        /// </summary>
        /// <param name="layout">The BuildLayout generated during a build</param>
        /// <returns>A list of the Bundle data defined in a BuildLayout</returns>
        public static IEnumerable<BuildLayout.Bundle> EnumerateBundles(LayoutLookupTables LayoutLookupTables)
        {
            foreach (BuildLayout.Bundle b in LayoutLookupTables.Bundles.Values)
                yield return b;
        }

        /// <summary>
        /// Gather a list of File data defined in a BuildLayout
        /// </summary>
        /// <param name="layout">The BuildLayout generated during a build</param>
        /// <returns>A list of File data</returns>
        public static IEnumerable<BuildLayout.File> EnumerateFiles(LayoutLookupTables LayoutLookupTables)
        {
            return EnumerateBundles(LayoutLookupTables).SelectMany(b => b.Files);
        }
    }
    
}
